import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { PropsWithChildren } from "react";
import QueryProvider from "./componentes/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juego",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
